# Generated by Django 4.1.7 on 2023-03-17 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_created_at'),
        ('posts', '0003_post_ispublish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='Dislikes', to='user.profile', verbose_name='Beğenmeyenler'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='Likes', to='user.profile', verbose_name='Beğenenler'),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Yazar'),
        ),
    ]
